config/routes.rb
RebelOutpost::Application.routes.draw do

  root to: 'pages#home'

  resources :messages, only: [:new, :create]

  get 'contact',  to: 'messages#new'
  get 'services', to: 'pages#services'
  get 'process',  to: 'pages#process'
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :name, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new

  end

  def create

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RebelOutpost
    %link{href: "http://fonts.googleapis.com/css?family=Enriqueta", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row
      .container
        .span4
          #logo
            = image_tag('rologo.png')
        .span7
          #nav
            = render 'shared/navigation'

    = yield
    .row#footer
      = render 'shared/footer'

app/views/pages/home.html.haml
#home
  .container  
    .row
      .span12
        .title
          We build
          %br
          state of the art 
          %br
          custom websites 
          %br
          and web applications

  #strip
    .container
      .row
        .span4.center
          %h2 How do we do it?
          %p
            We build our web applications and websites using Ruby on Rails and other modern web technologies. At Rebel Oupost, we take your web application and website dreams and make them a reality.
          

        .span4.center
          %h2 Who is Rebel Outpost?
          %p
            Rebel Outpost is a Web Development company based in Phoenix, AZ specializing in top of the line Ruby on Rails development. Click here to learn about the various services that we offer.
          

        .span4.center
          %h2 Want to know more?
          %p
            If you have an idea and want to talk about it, we would love to talk to you. If you have any questions about us or what we do, feel free to give us a call or send us a message.
          
      .row
        .span4.center
          %h3 Learn More
        .span4.center
          %h3 More About Us
        .span4.center
          %h3 Contact Us


  #about
    .container

app/views/pages/process.html.haml
#pages
  .container
    .row
      .span12
        %h1 How We Do It

app/views/pages/services.html.haml
#pages
  .container
    .row
      .span12
        %h1 What We Do

    .row
      .span12
        %h2 Ruby On Rails

app/views/shared/_footer.html.haml
.container.center
  .row
    &copy 2011-2013 Rebel Outpost 
  .row
    %ul#social
      %li= image_tag("twitter.png")
      %li= image_tag("facebook.png")
      %li= image_tag("linkedin.png")

app/views/shared/_navigation.html.haml
%ul
  %li= link_to "Home", root_path
  %li= link_to "Services", services_path
  %li= link_to "Process", process_path
  %li= link_to "Contact", contact_path